# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 11:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('nom_post', models.CharField(max_length=40, verbose_name='Nom Noticia')),
                ('descr_post', models.TextField(max_length=250, verbose_name='Descripcio')),
                ('data_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('foto_post', models.ImageField(upload_to='uploads', verbose_name='Imatge_Noticia')),
                ('autor_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nom_post'],
            },
        ),
    ]
